//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TomatoAnalyzer.rc
//
#define IDINDIV                         3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CONTROL_WINDOW              101
#define IDR_HTML_POINTYLEVEL            104
#define IDR_HTML_PCAPOINTS              105
#define IDD_COLORRANGEDIALOG            106
#define ID_PROGRESS_BAR                 107
#define IDR_MAINFRAME                   128
#define IDS_GROUP_L_RANGES              129
#define IDR_OSU_TOMATO                  130
#define IDS_GROUP_HUE_RANGES            130
#define IDS_GROUP_CHROMA_RANGES         131
#define IDR_ZOOMMENU                    132
#define IDS_GROUP_COLOR_USER_RANGES     132
#define IDS_MEAS_CURVED_FRUIT_SHAPE_INDEX 133
#define IDD_SLICEINFO                   134
#define IDS_PEPPER_PERICARP_AREA_RATIO  134
#define IDD_PROGRESS_DIALOG             135
#define IDS_PEPPER_PERICARP_THICKNESS_RATIO 135
#define IDD_PARAMETER                   139
#define IDI_SMALL_TOMATO                141
#define IDB_DELETE_FLAG                 142
#define IDB_PATTERN                     143
#define IDD_SAVEDATADLG                 144
#define IDD_SCANNER_DPI                 145
#define IDB_TEST                        148
#define IDD_BLOCKINESS                  149
#define IDD_SAVEDATA_DLG                150
#define IDD_SLICEINFO_DLG               151
#define IDB_LEGEND                      152
#define IDB_CHECKBOX_STATE              163
#define IDD_SELECT_MEASUREMENT          164
#define IDB_LEGEND1                     164
#define IDD_LEVEL_CONTROL               165
#define IDD_COLORTEST                   167
#define IDD_STARTUP                     171
#define IDD_LEVEL_CONTROL1              172
#define IDD_PCA_POINTS                  176
#define IDD_DIALOG1                     177
#define IDD_ELLIPSE_SIZE                177
#define IDD_DIALOG2                     178
#define IDD_PERICARPSIZE                181
#define IDB_BITMAP1                     182
#define IDB_BITMAP2                     183
#define IDD_BATCH_DIALOG                184
#define IDD_BATCH                       185
#define IDD_ADDFIELD                    186
#define IDD_ADDDATA                     187
#define IDD_LAB_DIALOG                  188
#define IDD_EDITCOL                     189
#define IDD_OLDTMT                      190
#define IDS_MEAS_PERIMETER              191
#define IDS_MEAS_AREA                   192
#define IDS_MEAS_WIDTH_MIDHEIGHT        193
#define IDS_MEAS_MAXIMUM_WIDTH          194
#define IDD_DIALOG3                     194
#define IDD_MANUAL_DPI                  194
#define IDS_MEAS_HEIGHT_MIDWIDTH        195
#define IDS_MEAS_MAXIMUM_HEIGHT         196
#define IDS_MEAS_CURVED_LENGTH          197
#define IDS_MEAS_FRUIT_SHAPE_INDEX_EXTERNAL_I 198
#define IDS_MEAS_FRUIT_SHAPE_EXTERNAL_II 199
#define IDS_MEAS_FRUIT_SHAPE_INDEX_EXTERNAL_II 199
#define IDD_DIALOG4                     199
#define IDD_MAN_DPI                     199
#define IDS_MEAS_PROXIMAL_FRUIT_BLOCKINESS 200
#define IDS_MEAS_DISTAL_FRUIT_BLOCKINESS 201
#define IDD_POST_DPI                    201
#define IDS_MEAS_FRUIT_SHAPE_TRIANGLE   202
#define IDS_MEAS_ELLIPSOID              203
#define IDS_MEAS_CIRCULAR               204
#define IDS_MEAS_RECTANGULAR            205
#define IDS_MEAS_HEART_SHAPE            206
#define IDS_MEAS_SHOULDER_HEIGHT        207
#define IDS_MEAS_PROXIMAL_ANGLE_MICRO   208
#define IDS_MEAS_PROXIMAL_ANGLE_MACRO   209
#define IDS_MEAS_DISTAL_ANGLE_MICRO     210
#define IDS_MEAS_DISTAL_ANGLE_MACRO     211
#define IDS_MEAS_DISTAL_INDENTATION_AREA 212
#define IDS_MEAS_PROXIMAL_INDENTATION_AREA 213
#define IDS_MEAS_DISTAL_END_PROTRUSION  214
#define IDS_MEAS_OBOVOID                215
#define IDS_MEAS_OVOID                  216
#define IDS_MEAS_V_ASYMMETRY            217
#define IDS_MEAS_H_ASYMMETRY_OBOVOID    218
#define IDS_MEAS_H_ASYMMETRY_OVOID      219
#define IDS_MEAS_WIDTH_WIDEST_POS       220
#define IDS_MEAS_ECCENTRICITY           221
#define IDS_MEAS_PROXIMAL_ECCENTRICITY  222
#define IDS_MEAS_DISTAL_ECCENTRICITY    223
#define IDS_MEAS_FRUIT_SHAPE_INDEX_INTERNAL 224
#define IDS_MEAS_ECCENTRICITY_AREA_INDEX 225
#define IDS_MEAS_LOBEDNESS_DEGREE       226
#define IDS_MEAS_PERICARP_AREA          227
#define IDS_MEAS_PERICARP_THICKNESS     228
#define IDS_MEAS_PERCENT_OF_PARAMETER_1 229
#define IDS_MEAS_PERCENT_OF_PARAMETER_2 230
#define IDS_MEAS_AVERAGE_RED            231
#define IDS_MEAS_AVERAGE_GREEN          232
#define IDS_MEAS_AVERAGE_BLUE           233
#define IDS_MEAS_AVERAGE_LUMINOSITY     234
#define IDS_MEAS_AVERAGE_L_VALUE        235
#define IDS_MEAS_AVERAGE_A_VALUE        236
#define IDS_MEAS_AVERAGE_B_VALUE        237
#define IDS_MEAS_AVERAGE_HUE            238
#define IDS_MEAS_AVERAGE_CHROMA         239
#define IDS_GROUP_BASIC_MEASUREMENTS    240
#define IDS_GROUP_FRUIT_SHAPE_INDEX     241
#define IDS_GROUP_BLOCKINESS            242
#define IDS_GROUP_HOMOGENEITY           243
#define IDS_GROUP_PROXIMAL_FRUIT_END_SHAPE 244
#define IDS_GROUP_DISTAL_FRUIT_END_SHAPE 245
#define IDS_GROUP_ASYMMETRY             246
#define IDS_GROUP_INTERNAL_ECCENTRICITY 247
#define IDS_GROUP_LATITUDINAL_SECTION   248
#define IDS_GROUP_MORPHOMETRICS         249
#define IDS_GROUP_COLOR_ANALYSIS        250
#define IDS_GROUP_USER_CREATED          251
#define IDS_MEAS_PERICARP_AREA_RATIO    252
#define IDS_MEAS_PERICARP_THICKNESS_RATIO 253
#define IDS_MEAS_PERICARP_BOUNDARY_LENGTH 254

#define IDS_MEAS_REAL_PERICARP_AREA     255
#define IDS_MEAS_REAL_PERICARP_THICKNESS 256
#define IDC_SLICEINFO_LIST              1002
#define IDC_CURVE_THRESHOLD             1004
#define IDC_Candidates                  1005
#define IDC_Selected                    1006
#define IDC_ADD                         1007
#define IDC_REMOVE                      1008
#define IDC_SAVEDATA_UP                 1009
#define IDC_SAVEDATA_DOWN               1010
#define IDC_SCANNER_DPI                 1011
#define IDC_SHAPEINDEX                  1012
#define IDC_UNIT_SELECTION              1012
#define IDC_UPPER                       1013
#define IDC_LOWER                       1014
#define IDC_SELECTION_TREE              1015
#define IDC_PAGE                        1016
#define IDC_TAB1                        1017
#define IDC_LIST1                       1018
#define IDC_LIST2                       1019
#define IDC_TREE1                       1021
#define IDC_SELECT_ALL                  1022
#define IDC_SLIDER_MACRO                1023
#define IDC_SLIDER_MICRO                1024
#define IDC_MACRO_VALUE                 1025
#define IDC_MICRO_VALUE                 1026
#define IDC_GRAPH                       1027
#define IDC_EDIT1                       1032
#define IDC_EDIT2                       1033
#define IDC_LOWERL2                     1033
#define IDC_DATACOL5                    1034
#define IDC_LOWERHUE1                   1034
#define IDC_DATACOL7                    1035
#define IDC_LOWERCHROMA1                1035
#define IDC_DATACOL4                    1036
#define IDC_LOWERHUE2                   1036
#define IDC_DATACOL8                    1037
#define IDC_LOWERCHROMA2                1037
#define IDC_DATACOL10                   1038
#define IDC_LOWERL3                     1038
#define IDC_DATACOL11                   1039
#define IDC_LOWERHUE3                   1039
#define IDC_DATACOL13                   1040
#define IDC_LOWERCHROMA3                1040
#define IDC_CHECKBATCH                  1041
#define IDC_DATACOL14                   1041
#define IDC_LOWERL4                     1041
#define IDC_DATACOL3                    1042
#define IDC_LOWERHUE4                   1042
#define IDC_DATACOL6                    1043
#define IDC_LOWERCHROMA4                1043
#define IDC_EDIT3                       1044
#define IDC_UPPERL1                     1044
#define IDC_BUTTON1                     1045
#define IDC_DATACOL12                   1045
#define IDC_SAVE_SETTINGS               1045
#define IDC_UPPERHUE1                   1045
#define IDC_FILE                        1045
#define IDC_HISTO_PERCENT               1046
#define IDC_EDIT4                       1046
#define IDC_L_SLOPE                     1046
#define IDC_UPPERCHROMA1                1046
#define IDC_RICHEDIT21                  1047
#define IDC_EDIT12                      1047
#define IDC_A_SLOPE                     1047
#define IDC_UPPERL2                     1047
#define IDC_PROGRESS_CON                1048
#define IDC_EDIT13                      1048
#define IDC_B_SLOPE                     1048
#define IDC_UPPERHUE2                   1048
#define IDC_MESSAGE                     1049
#define IDC_SPIN1                       1049
#define IDC_EDIT14                      1049
#define IDC_L_INTERCEPT                 1049
#define IDC_UPPERCHROMA2                1049
#define IDC_SLIDER1                     1050
#define IDC_EDIT15                      1050
#define IDC_A_INTERCEPT                 1050
#define IDC_UPPERL3                     1050
#define IDC_CUSTOM1                     1051
#define IDC_EDIT16                      1051
#define IDC_B_INTERCEPT                 1051
#define IDC_UPPERHUE3                   1051
#define IDC_UPPERCHROMA3                1052
#define IDC_UPPERL4                     1053
#define IDC_RADIO2                      1054
#define IDC_ILLUMINANT_2                1054
#define IDC_UPPERHUE4                   1054
#define IDC_C_2                         1054
#define IDC_RADIO3                      1055
#define IDC_INDIV                       1055
#define IDC_UPPERCHROMA4                1055
#define IDC_ILLUMINANT_3                1055
#define IDC_D65_2                       1055
#define IDC_EDIT5                       1056
#define IDC_LOWERL5                     1056
#define IDC_EDIT6                       1057
#define IDC_RADIO1                      1057
#define IDC_ILLUMINANT_10               1057
#define IDC_UPPERL5                     1057
#define IDC_D65_10                      1057
#define IDC_EDIT7                       1058
#define IDC_STATIC1                     1058
#define IDC_LOWERHUE5                   1058
#define IDC_EDIT8                       1059
#define IDC_UPPERHUE5                   1059
#define IDC_EDIT9                       1060
#define IDBASIC                         1060
#define IDC_LOWERCHROMA5                1060
#define IDC_EDIT10                      1061
#define IDSTD                           1061
#define IDC_UPPERCHROMA5                1061
#define IDC_NUM_UNITS                   100000
#define IDC_EDIT11                      1062
#define IDC_BASIC                       1062
#define IDC_LOWERL6                     1062
#define IDC_STD                         1063
#define IDC_UPPERL6                     1063
#define IDC_LOWERHUE6                   1064
#define IDC_ADDF_LABEL1                 1065
#define IDC_UPPERHUE6                   1065
#define IDC_ADDF_MEASURE1               1066
#define IDC_LOWERCHROMA6                1066
#define IDC_ADDF_LABEL2                 1067
#define IDC_FINISH                      1067
#define IDC_UPPERCHROMA6                1067
#define IDC_ADDF_MEASURE2               1068
#define IDC_COMBO1                      1068
#define IDC_COMBO2                      1069
#define IDC_ADDF_LABEL3                 1071
#define IDC_PALETTE                     1071
#define IDC_ADDF_CHBOX3                 1072
#define IDC_ADDF_MEASURE3               1072
#define IDC_LSTAR_BOX                   1072
#define IDC_ASTAR_BOX                   1073
#define IDC_BSTAR_BOX                   1074
#define IDC_LSTAR_TEXT                  1075
#define IDC_ASTAR_TEXT                  1076
#define IDC_BSTAR_TEXT                  1077
#define IDC_EDIT                        1078
#define ID_OK1                          1079
#define IDC_COLLIST                     1080
#define IDC_COLLABEL                    1081
#define IDC_DATACOL1                    1082
#define IDC_DATACOL2                    1083
#define IDC_DATACOL9                    1084
#define IDC_DATACOL15                   1085
#define IDC_DATACOL16                   1086
#define IDC_CALIBRATE                   1086
#define IDC_DATACOL17                   1087
#define IDC_DATACOL18                   1088
#define IDC_DATACOL19                   1089
#define IDC_DATACOL20                   1090
#define IDC_DATACOL21                   1091
#define IDC_CALIBRATION_MESSAGE         1091
#define IDC_DATACOL22                   1092
#define IDC_DATACOL23                   1093
#define IDC_DATACOL24                   1094
#define IDC_RESTORE_DEFAULTS            1094
#define IDC_DATACOL25                   1095
#define IDC_ANALYZE_COLOR               1095
#define IDC_DATACOL26                   1096
#define IDC_NEXT                        1096
#define IDC_DATACOL27                   1097
#define IDC_DATACOL28                   1098
#define IDC_DEFAULT_RANGES              1098
#define IDC_DATACOL29                   1099
#define IDC_USER_RANGES                 1099
#define IDC_DATACOL30                   1100
#define IDC_LOWERL1                     1100
#define IDC_CLEAR                       1102
#define IDC_COMBOBOXEX1                 1103
#define IDC_MEASURE_BOX                 1105
#define IDC_MANUAL_DPI                  1106
#define ID_ANALYZE_IMG                  32771
#define ID_FILE_PREV                    32772
#define ID_FILE_NEXT                    32773
#define ID_ZOOM                         32774
#define ID_ZOOM25                       32775
#define ID_ZOOM50                       32776
#define ID_ZOOM80                       32777
#define ID_ZOOM100                      32778
#define ID_ZOOM150                      32779
#define ID_ZOOM200                      32780
#define ID_EXPORT_DATA                  32782
#define ID_PROCESS_IMG                  32783
#define ID_SYSTEM_SETTING               32784
#define ID_MANUAL_REVISE                32801
#define ID_MANUAL_ROTATE                32802
#define ID_MANUAL_SHAPE                 32803
#define IDC_DATA_SELECTION              32808
#define ID_ANALYZE_SINGLE               32809
#define IDC_ANALYZE_BATCH               32810
#define ID_ANALYZE                      32811
#define IDC_BLOCKINESS_POS              32812
#define ID_MANUAL_RESET_ROTATE          32813
#define ID_MANUAL_RESET_SHAPE           32814
#define ID_MANUAL_ANGLE_STEM            32815
#define ID_MANUAL_ANGLE_FIRST           32815
#define ID_MANUAL_ANGLE_BLM             32816
#define ID_MANUAL_BLM_LARGE             32817
#define ID_MANUAL_ANGLE_LAST            32817
#define ID_SAVE_FRUIT                   32820
#define ID_IMAGE_CLOSE                  32821
#define IDC_POINTI_LEVEL                32861
#define ID_ADJUST_TIPAREA               32863
#define ID_AUTO_ROTATE                  32865
#define IDC_COLORTEST                   32867
#define ID_REVISE_RESETAUTO             32869
#define ID_Menu                         32870
#define ID_Menu32871                    32871
#define ID_COLORTEST_ANALYZE            32874
#define ID_HELP_DISCLAIMER              32877
#define ID_USERSETTINGS_LOADSETTINGS    32880
#define ID_USERSETTINGS_SAVESETTINGS    32881
#define ID_BUTTON32882                  32882
#define ID_SETTINGS_EXPORTPCAPOINTS     32884
#define ID_REVISE_ADJUSTELLIPSE         32885
#define ID_REVISE_ADJUSTTIPAREA         32886
#define ID_REVISE_RESETELLIPSE          32887
#define ID_REVISE_RESETTIPAREA          32888
#define ID_SETTINGS_DEFAULTELLIPSESIZE  32889
#define ID_ELIMINATE                    32891
#define ID_INNER_BOUNDARY               32893
#define ID_RESETINNER                   32894
#define ID_DEFAULTPERICARP              32896
#define ID_PERICARPSIZE                 32897
#define ID_SETTINGS_ADDFIELD            32898
#define ID_ADD_FIELD                    32899
#define ID_DATA_ADDFIELD                32900
#define IDC_DATA_ADDFIELD               32901
#define ID_USERCREATEDFUNCTIONS_ADDDATA 32902
#define IDC_ADDINFO                     32903
#define IDC_DATA_ADDINFO                32904
#define ID_SETTINGS_COLORFEATURES       32905
#define ID_COLORFEATURES_ENTERL         32906
#define ID_                             32907
#define ID_LAB_ENTER                    32908
#define ID_ANALYZE_COLOR                32910
#define ID_ANALYZE_ANALYZECOLOR         32911
#define ID_FLAT_PROXIMAL_MICRO          32912
#define ID_FLAT_PROXIMAL_MACRO          32913
#define ID_FLAT_DISTAL_MICRO            32914
#define ID_FLAT_DISTAL_MACRO            32915
#define ID_SETTINGS_MANUALLYSELECTDPI   32915
#define ID_RESET_PROXIMAL_MICRO         32916
#define ID_SETTINGS_MANUALLYCALIBRATETHEDPI 32916
#define ID_RESET_PROXIMAL_MACRO         32917
#define ID_SETTINGS_MANUALLYSELECTTHEDPI 32917
#define ID_RESET_DISTAL_MICRO           32918
#define ID_MANUAL_DPI                   32918
#define ID_RESET_DISTAL_MACRO           32919
#define ID_USER_DPI                     32919
#define ID_PEPPER_PERICARP              32920
#define ID_RESET_PEPPER_PERICARP        32921
#define IDC_USER_DPI                    32922

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32920
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
